baseURL = "https://lightbi-hugo-theme.netlify.app/"
DefaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
languageCode = "en-us"
title = "Bookish Musings by A"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
#pygmentsUseClasses = true
#pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
#googleAnalytics = "XXX"
enableRobotsTXT = true
enableGitInfo = false
Paginate = 3
summaryLength  = "30"

[Params]
selfHosted = true
mainSections = ["post","posts"]
dateFormat = "02 January 2006"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true
summaryLength  = "9"
lunrSearch = true
gcse = false
lastmod = false
rss = false
hideAuthor = false
description="Welcome to my book blog :)"
previewCardImagePlacement = "bottom"

[Params.Author]
  name = "Booking Musings by A"
  website = "https://www.bookishmusingsbya.substack.com/"
  authorInfo = """Welcome to my book blog :)"""
  authorPostImage = "/img/author-about.jpg"


[Author]
  name = "A"
  website = "https://bookishmusingsbya.substack.com"

[[menu.main]]
    name = "home"
    url = "/home/"
    weight = 1

[[menu.main]]
    name = "reviews"
    url = "/reviews/"
    weight = 3

[[menu.main]]
    name = "fireside chats"
    url = "/rants/"
    weight = 4

[[menu.main]]
    name = "roundups"
    url = "/roundups/"
    weight = 5

[[menu.main]]
    name = "about"
    url = "/about/"
    weight = 2
    
[[menu.main]]
    name = "subscribe!"
    url = "/subscribe/"
    weight = 6



[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

